[package]
name = "isa_interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
pretty_assertions = "1.4.0"
dot-writer = "0.1.3"
clap = { version = "4.2.1", features = ["cargo"] }
stacker = "0.1.15"
rand = "0.8.5"
